### ISSUE TITLE
Create table for ontology annotations

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#20] opened 2019-12-02 16:32 UTC
For each of the variables (phenotypes, environmental) in the initial datasets, please create a spreadsheet that combines all combinations of variables.name, variables.description, variables.units, methods.name, and methods.description. 

Then ask Pankaj to annotate these

**Comment by MagicMilly** [comment] 2019-12-03 00:01
Closing this - duplicate of Issue #9

**Closed as completed by MagicMilly** 2019-12-03 00:01 UTC
